  [workspace]
  resolver = "2"

  members = [ "crates/providers/rust_client",
    "crates/providers/sacloud-rs",
    "crates/tui",
  ]

  # The profile that 'dist' will build with
  [profile.dist]
  inherits = "release"
  lto = "thin"

[workspace.metadata.dist]
ci.runner = "ubuntu-24.04"
