[package]
name = "rust-client"
version = "0.1.0"
edition = "2024"

[dependencies]
chiral-client = "0.1.0"
tonic = "0.11"
serde_json = "1"

[build-dependencies]
tonic-build = "0.11"
prost-build = "0.12"

